server.port: 8183
spring.cloud.stream.bindings:
  process-in-0:
        destination: appliance-topic
  process-out-0:
        destination: brand-topic
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    commit.interval.ms: 1000
  serdeError: logAndContinue
spring.cloud.stream.kafka.streams.bindings:
  process-in-0:
    consumer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: csci318.demo.model.Appliance
  process-out-0:
    producer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: csci318.demo.model.BrandQuantity

#spring.cloud.stream.kafka.streams.binder.stateStoreRetry.maxAttempts: 3



