server.port: 8081
spring.cloud.stream:
  bindings:
    order-outbound:
      destination: order-topic
  kafka.binder:
    configuration:
      commit.interval.ms: 1000
    brokers: localhost:9092
    serdeError: logAndContinue
  kafka.bindings:
    order-outbound:
      producer:
        configuration:
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: com.example.orderservice.entities.KafkaEvent